### ISSUE TITLE
Having trouble installing txjsonrpc via pip

### ISSUE THREAD

**Issue by archit** [oubiwann/txjsonrpc#24]
I'm running this on Ubuntu 14.04 LTS.
```
archit@ip-10-0-1-117:~$ python --version
Python 2.7.6
archit@ip-10-0-1-117:~$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
archit@ip-10-0-1-117:~$ sudo pip install txJSON-RPC==0.3.1
The directory '/home/archit/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/archit/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting txJSON-RPC==0.3.1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading txJSON-RPC-0.3.1.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 5.9MB/s 
    Complete output from command python setup.py egg_info:
    Warning: '%s' not a legal ReST filename.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5ZujeA/txJSON-RPC/setup.py", line 25, in <module>
        out=True),
      File "txjsonrpc/util/dist.py", line 117, in catReST
        report = validateReST(res)
      File "txjsonrpc/util/dist.py", line 82, in validateReST
        return _validateReST(text)
      File "txjsonrpc/util/dist.py", line 72, in _validateReST
        parser.parse(text, doc)
      File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 185, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 157, in run
        inliner.init_customizations(document.settings)
      File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
        if settings.character_level_inline_markup:
    AttributeError: Values instance has no attribute 'character_level_inline_markup'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5ZujeA/txJSON-RPC/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
archit@ip-10-0-1-117:~$ 
```

**Comment by iserko** [comment]
@archit the `docutils` package had a bug, and they've fixed it in svn version 8060 ... https://sourceforge.net/p/docutils/code/8060/tree//trunk/docutils/docutils/parsers/rst/states.py?diff=5140ec3227184634283d9030:8059

Bug tracker link: https://sourceforge.net/p/docutils/bugs/304/

What I did was download the docutils tarball and `python setup.py install` inside the `docutils` package and solved it for me.
